### ISSUE TITLE
Crash when using Remonsterate

### ISSUE THREAD

**Issue by MadPixelGamer** [FF6BeyondChaos/BeyondChaosRandomizer#88]
Rolling seed 1 of 1.
3|normal|bcdegijklmnopqrstwyz makeover partyparty alasdraco capslockoff johnnydmad notawaiter mimetime remonsterate|1648164726
You are using Beyond Chaos CE Randomizer version "3".
Using seed: 3|normal|bcdegijklmnopqrstwyz makeover partyparty alasdraco capslockoff johnnydmad notawaiter mimetime remonsterate|1648164726
SECRET CODE: SPRITE REPLACEMENT MODE ACTIVATED
SECRET CODE: CRAZY PARTY MODE ACTIVATED
SECRET CODE: JAM UP YOUR OPERA MODE ACTIVATED
SECRET CODE: Mixed Case Names Mode ACTIVATED
SECRET CODE: MUSIC REPLACEMENT MODE ACTIVATED
SECRET CODE: CUTSCENE SKIPS ACTIVATED
SECRET CODE: ALTERNATE GOGO MODE ACTIVATED
SECRET CODE: MONSTER SPRITE REPLACEMENT MODE ACTIVATED

Now beginning randomization.
The randomization is very thorough, so it may take some time.
Please be patient and wait for "randomization successful" to appear.
Cutscenes are currently skipped up to Kefka @ Narshe
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 121, in worker
  File "randomizer.py", line 5283, in randomize
NameError: name 'bcmultiprocessing' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "beyondchaos.py", line 1270, in generateSeed
  File "multiprocessing\pool.py", line 657, in get
NameError: name 'bcmultiprocessing' is not defined

**Comment by DarkSlash88** [comment]
Fixed in newest version. Thanks for the report!
